### ISSUE TITLE
Create a wiki, explaining the common usage scenarios.

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/clad#22]

**Comment by efremale** [comment]
Is it fixed with #130?

**Comment by vgvassilev** [comment]
I'd say partially, we are still missing the internals of clad, and a few cases where differentiation is useful and how clad can be used. For example, the ray tracer demo shows derivatives in the domain of computer graphics. We lack explanation in text how to wire clad in that case. I'd imagine we enumerate 2-3 more such domains.

**Comment by vgvassilev** [comment]
That's covered well enough in the README nowadays.
